# This config is *heavily* inspired by rwxrob

# Set terminal colors
set-option -g default-terminal "screen-256color"

# Set escape-time delay to 0ms
set -sg escape-time 0

# Key bindings

# Reload configuration using `r`
bind -r r source-file ~/.tmux.conf

# Use `-` for horizontal pane splitting
unbind -
unbind _
bind - split-window -v
bind _ split-window -v

# Use `|` for vertical pane splitting
unbind |
bind | split-window -h
bind '\' split-window -h
bind 'C-\' split-window -h

# Navigate panes using vi motions
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Resize panes using vi motions
bind -r C-k resize-pane -U 1
bind -r C-j resize-pane -D 1
bind -r C-h resize-pane -L 1
bind -r C-l resize-pane -R 1

# Avoid cursor movement when resizing
set -g repeat-time 200

set -g mode-keys vi
set -g status-keys vi

# Kill window including panes
bind-key & kill-window

# Panes

# Start panes with index 1
set -g base-index 1
setw -g pane-base-index 1

# Styling

# Selection background color
set -g mode-style "bg=black"

# Pane borders
set -g pane-border-style "fg=#171717"
set -g pane-active-border-style "fg=#171717"

# Status bar
set -g status-position top
set -g status-justify left

# Disable some stuff
set -g status-left ''
set -g status-right ''

# Set status colors
set -g status-style 'fg=colour0 bg=#1b1b1b'
set -g window-status-current-style 'fg=colour0'

# Messages
set -g message-style 'fg=colour0 bg=#1b1b1b'

