#!/usr/bin/env bash

set -e

# Set up tmux configuration including plugins.

TPM_DIR=~/.tmux/plugins/tpm
if [[ ! -d $TPM_DIR ]]; then
	git clone https://github.com/tmux-plugins/tpm $TPM_DIR
fi

mkdir -p ~/.config/tmux
ln -sf "$PWD/tmux/tmux.conf" "$HOME/.config/tmux/tmux.conf"

# Set up neovim configuration.

ln -sf "$PWD/nvim" "$HOME/.config/nvim"

# Set up ideavim configuration.

ln -sf "$PWD/idea/ideavimrc" "$HOME/.ideavimrc"
