#!/usr/bin/env bash

cd "$ZETTEL" || exit

timestamp="$(date +"%y%m%d%H%M%S")"
filename="${timestamp}.md"

touch "$ZETTEL/$filename"
{
	echo "---"
	echo "id: \"$timestamp\""
	echo "aliases:"
	echo "tags:"
	echo "---"
	echo "# "
	echo -en "\n"
	echo "---"
	echo "# References"

} >>"$ZETTEL/$filename"

nvim '+ normal 6G$' "$ZETTEL/$filename"
